#!/bin/sh
set -eu

if { [ "${1:-}" = remove ] || [ "${1:-}" = deconfigure ]; } && [ -d /run/systemd/system ]; then
  systemctl stop dotlet.service dotlet-named.service 2>/dev/null || true
  systemctl disable dotlet.service dotlet-named.service 2>/dev/null || true
fi

exit 0
